### ISSUE TITLE
Locking does nothing

### ISSUE THREAD

**Issue by fmorett** [slinger360/NineRiFt-kivy#3]
If locking is pressed nothing happens on windows.

**Comment by HelaFaye** [comment]
First of all, donate and I'll give a damn about noob questions(haven't ate in two days and I literally have only $0.64 in my bank account). Second, the no-lock spinner is to set whether you need to lock the vehicle during the update process (if it's already locked and you issue the lock command, you get an error because it's already locked and NineRiFt received an invalid response to the lock command).

**Comment by fmorett** [comment]
Ok I'm very sorry to have boughtered you. I'm thankful though for the explanation.

**Comment by HelaFaye** [comment]
I'm working on the command screen (that will include lock, unlock, reboot, and poweroff) but, it's difficult to focus when the last thing one ate was a bagel and that was 2 days ago.
